version: '3.4'

networks:
  api-net:
    driver: bridge

services:
  s_api:
    container_name: c_api
    image: ${DOCKER_REGISTRY-}api
    build:
      context: .
      dockerfile: Api/Dockerfile
    environment:
      - ConnectionStrings__DefaultConnection=Server=s_postgredb;Port=5432;Database=DepremAppDb;User Id=root;Password=root;
    ports:
      - "7147:80"
    depends_on:
      - s_postgredb
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
    networks:
      - api-net

  s_postgredb:
    container_name: c_postgre
    image: postgres:latest
    ports:
      - "5432:5432"
    restart: always
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: "root"
      POSTGRES_PASSWORD: "root"
      POSTGRES_DB: "DepremAppDb"
    networks:
      - api-net

  pgadmin:
    container_name: c_pgadmin
    image: dpage/pgadmin4
    restart: always
    ports:
      - "85:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: depremapp@mail.com
      PGADMIN_DEFAULT_PASSWORD: 1q2w3e4r5T
    networks:
      - api-net